### ISSUE TITLE
code stuck?

### ISSUE THREAD

**Issue by nbecker** [schollz/meanrecipe#3]
1st try, seems to just get stuck
```
python3 run.py --recipe 'sweet potato soup'
```

Runs as far as
```
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▊| 1199/1201 [06:00<00:00,  3.24it/s]
1199it [06:00,  3.33it/s]
```
Then seems to hang.  100% cpu used by pandoc, but seems to be making no progress.

I had tried your example
```
python3 run.py --recipe brownies
```
which ran to completion OK

**Comment by schollz** [comment]
Yeah I don't know why it does this. Just run it again though and it will work. Definitely a bug

**Comment by nbecker** [comment]
Seem if I kill and restart it runs to completion, but now shows another I believe bug.  The recipes call for like 2 cups of garlic!  I think it is confused trying to combined recipes calling for N cups of garlic with ones calling for M whole cloves

**Comment by schollz** [comment]
Yeah, garlic is going to be one of those weird edge cases. It's kinda like eggs because it requires sometimes be specified as "whole cloves" instead of "cups".
