### ISSUE TITLE
Website Down

### ISSUE THREAD

**Issue by ankane** [schollz/meanrecipe#9]
Hey @schollz, neat project!

The link in the readme works (https://averagecookbook.schollz.com/), but the link in the project description (https://www.averagecookbook.com) errors with `ERR_CONNECTION_REFUSED`.

**Comment by schollz** [comment]
@ankane Thanks! Yeah I lost that domain, here's the new link: https://meanrecipe.schollz.com

**Comment by ankane** [comment]
Bummer. Would be good to update the description when you have a chance.
![Screen Shot 2019-04-24 at 9 12 04 PM](https://user-images.githubusercontent.com/220358/56709423-1867c880-66d6-11e9-85aa-dbef4ccfec79.png)

**Comment by schollz** [comment]
@ankane Got it thanks!
